version: "3"
services:
  app:
    build: .
    ports:
      - 8080:8080
    restart: always
  database:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db
    restart: always